Claims data profiling - add grain level models
tuva-health/data_profiling pull request #3
Opened 2022-08-17 21:09 UTC by sarah-tuva

Build two new models for claims data profiling `eligibility` grain and `medical_claim` grain. Each model will have a row per record from the input layer with columns for each data quality check run. 

The goal is for these tables:
* Deep dives into data quality issues
* Can be joined in queries/pipelines to filter out bad records

2022-08-17 23:58 UTC, aneiderhiser commented on macros/valid_past_or_current_date_check.sql
> +    and {{ column_name }} between '1900-01-01' and getdate()::date
Maybe we change this to the year 2000?  I think we'll encounter very few datasets that are actually prior to the year 2000.

2022-08-18 00:02 UTC, aneiderhiser commented on models/claims/schema/claim_summary.yml
> +        - name: table_name
Can we delete this (table_name column duplicated)?

2022-08-18 00:09 UTC, aneiderhiser requested changes
I noticed 2 very minor things and left comments for them.

2022-08-18 13:00 UTC, thutuva commented on models/claims/claim_summary.sql
> +        select distinct patient_id, birth_date
The patients should be unique on ID alone.  If a patient has two birthdates it should be resolved or else we'd be duplicating their member months.  I know it will likely be difficult to determine what is the correct DOB but it will have to be done to avoid skewing analysis.

2022-08-18 13:00 UTC, thutuva commented on models/claims/claim_summary.sql
> +{% endset -%}
Is this a check on the primary key values in medical claim?  If so, I would change it to a count of claim_id and claim_line_number to ensure these two values are unique.

2022-08-18 13:00 UTC, thutuva commented on models/claims/eligibility_detail.sql
> +        from eligibility_src
Flagging this line if you agree with my earlier comment that patient_id alone should be unique.

2022-08-18 16:14 UTC, sarah-tuva commented on macros/valid_past_or_current_date_check.sql
> +    and {{ column_name }} between '1900-01-01' and getdate()::date
@aneiderhiser, I wasn't sure how far we would actually want to go back. I think 2000 is probably a good minimum date for claims. We will probably need a different check for clinical data, especially for clinical history. Like an old surgery or procedure being reported. This is a super basic date check that I would love to improve down the road.

2022-08-18 16:16 UTC, sarah-tuva commented on models/claims/schema/claim_summary.yml
> +        - name: table_name
@aneiderhiser Good catch!

2022-08-18 16:20 UTC, sarah-tuva commented on models/claims/claim_summary.sql
> +        select distinct patient_id, birth_date
@thutuva Thanks for your feedback. I was trying to figure out how to determine a unique patient_id on the member month grain. I think checking birth_date could help find data quality issues and it would have to be resolved in the source. Do you think I should instead look for distinct patient_id, month, and year? If we see more than one then that probably means it's a duplicate ID.

2022-08-18 16:23 UTC, sarah-tuva commented on models/claims/claim_summary.sql
> +{% endset -%}
@thutuva This is not a primary key check. The purpose of this var is to get the total count of unique claim_id's for some of the percentage calculations. I guess I could just `select count(distinct claim_id)` instead.

2022-08-18 16:25 UTC, sarah-tuva commented on models/claims/claim_summary.sql
> +        select distinct patient_id, birth_date
To add some more context. Just selecting distinct patient_id will not help find DQ issues. I need another field(s) to help confirm if the patient_id is being used for more than one person.

2022-08-18 16:39 UTC, thutuva commented on models/claims/claim_summary.sql
> +        select distinct patient_id, birth_date
Yea, I think I was interpreting this check wrong compared to it's actual purpose but I think I'm on the same page now.  I think they way you have it works but I would also consider patient_id and payer.

In the CO APCD data, I ran into issues with my pk/uniqueness check which is patient_id, month, and year.  It was because some patients had multiple insurance carrier which can happen when they want to supplement a plan with another.  Maybe leave this check how it is for now but just keep this scenario in mind when you get around to running it on the CO APCD?

2022-08-18 17:03 UTC, sarah-tuva commented on models/claims/claim_summary.sql
> +        select distinct patient_id, birth_date
@thutuva Oh, that's a good point. I completely neglected payer. I think that is a much more reliable check, in theory. Thank you for pointing it out. I will make that change now.

2022-08-18 17:46 UTC, sarah-tuva commented on models/claims/eligibility_detail.sql
> +        from eligibility_src
Updated to payer per conversation in other thread.

2022-08-18 21:35 UTC, aneiderhiser approved these changes

2022-08-18 21:35 UTC, merged